[book]
title = "Casper 2.0 (Condor) Knowledge Base"
authors = ["Casper Association"]
description = "A guide to Casper v2.0 (Condor)."
src = "src"
language = "en"
text-direction = "ltr"

[rust]
edition = "2018"

[build]
build-dir = "book"
create-missing = false

[preprocessor.index]

[preprocessor.links]

[output.html]
additional-css = ["custom.css"]

[output.html.search]
limit-results = 15
