[book]
title = "Casper 2.0 (Condor) Knowledge Base"
authors = ["Casper Association"]
description = "A guide to Casper v2.0 (Condor)."
src = "src"
language = "en"
text-direction = "ltr"

[rust]
edition = "2018"

[build]
build-dir = "book"
create-missing = false

[preprocessor.index]

[preprocessor.links]

[output.html]
default-theme = "dark"
preferred-dark-theme = "coal"
smart-punctuation = true
mathjax-support = false
copy-fonts = true
additional-css = ["./theme/catppuccin.css", "./theme/catppuccin-admonish.css"]
no-section-label = false
git-repository-url = "https://github.com/casper-network/condor-info"
git-repository-icon = "fa-github"
site-url = "/condor-info/"
input-404 = "not-found.md"

[output.html.search]
limit-results = 15
